pipeline {
    agent any

    tools {
        maven "maven3"
    }

    stages {
        stage('Build') {
            steps {
                // Get code from the GitHub repository
                git branch: 'main', url: 'https://github.com/TanvirMahmud01/comp367Mahmud-lab3.git'

                // Build the Maven project
                bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }
            post {
                success {
                    // Archive the JAR file generated by the Maven build
                    archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-password', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                // Build Docker image using the Dockerfile
                sh 'docker build -t tmt01/301106599-lab3 .'
            }
        }

        stage('Push Docker Image') {
            steps {
                // Push Docker image to Docker Hub
                sh 'docker push tmt01/301106599-lab3'
            }
        }
    }
}
